# Submit file
universe = docker
# link to self-built docker image
docker_image = yasuo0810/mndetection:v0.2

# set the executable to run
executable = ./run.sh
# set the log, error and output files
log = log/job$(Cluster).log
error = error/job$(Cluster).err
output = output/job$(Cluster).out

transfer_input_files = microdet.tar.gz
transfer_output_files = microdet/dataset_v2/model_output

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 1
request_gpus = 4

+WantGPULab = true
+GPUJobLength = "medium"

request_memory = 30GB
request_disk = 10GB

Requirements = (Machine == "jcaicedogpu0000.chtc.wisc.edu" || Machine == "jcaicedogpu0001.chtc.wisc.edu")
# Requirements = (Target.CUDADriverVersion >= 10.1)

queue