# Submit file
universe = docker
# link to self-built docker image
docker_image = yasuo0810/dinov2_chtc:v0.3

# set the executable to run
executable = ./run_training.sh
# set the log, error and output files
log = log/log$(Cluster).log
error = error/job$(Cluster).err
output = output/job$(Cluster).out

transfer_input_files = microdet.tar.gz
transfer_output_files = microdet/dataset_v2/model_output, microdet/train_output.txt

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

request_cpus = 1
request_gpus = 1

+WantGPULab = true
+GPUJobLength = "medium"

request_memory = 80GB
request_disk = 80GB

Requirements = (Machine == "jcaicedogpu0000.chtc.wisc.edu" || Machine == "jcaicedogpu0001.chtc.wisc.edu")

queue